version: '3'

services:
  web:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - "8081:80"
    depends_on:
      - db
    command: ["php", "artisan", "serve", "--host=0.0.0.0", "--port=80"]
  db:
    image: mysql:8.0.24
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: 7d331939cfcd0d5c
      MYSQL_USER: root
      MYSQL_PASSWORD: password
