version: '3'

services:
  web:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - "8181:8181"
    depends_on:
      - db
  db:
    image: mysql:8.0.24
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: 7d331939cfcd0d5c
      MYSQL_USER: root
      MYSQL_PASSWORD: password
